<a href="https://colab.research.google.com/github/nurulrezky/Pemrograman/blob/main/PDS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY

In [ ]:
#Manampilkan data
data = np.array([1, 2, 3])
data[1]
data[0:2]
data[1:]
data[-2:]

90

##Indexing and slicing

In [ ]:
#Manampilkan data
data = np.array([1, 2, 3])
data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

##ndarray.shape

In [ ]:
#Menampilkan array 2 dimensi setiap dimensi memiliki 3 elemen.
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [ ]:
a=np.array([[1,2,3,4],[5,66,7,8])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (1836193386.py, line 1)

In [ ]:
a=np.array([[1,2,3,4],[5,66,7,8]])
a.shape

(2, 4)

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
b

b = a.reshape(3,2) mengubah ukuran

SyntaxError: invalid syntax (325625178.py, line 5)

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
b

#b = a.reshape(3,2) mengubah ukuran matriks dari matrix 2x3 menjadi 3x2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,3)
b

#b = a.reshape(3,3) mengubah ukuran matriks dari matrix 2x3 menjadi 3x3

ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a.reshape(3,3)
b
#b = a.reshape(3,3) mengubah ukuran matriks menjadi 3×3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#membuat array sebanyak 24, dari 0-23 #~(0,24)
a = np.arange(24)
b = a.reshape(2, 3, 4)
b

ValueError: cannot reshape array of size 24 into shape (2,4,2)

In [ ]:
#Membuat array sebanyak 24, dari 0-23 #~(0,24)
a = np.arange(24)
b = a.reshape(2, 4, 3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

##numpy.arange

In [ ]:
a = np.arange(24)
a
#Membuat array berurutan dengan nilai mulai dari 0 hingga jumlah elemen yang ditentukan sebagai argumen.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
#Membuat array dengan arange
np.arange(3,7)

array([3, 4, 5, 6])

In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
np.arange(2,12,3)
 #2: awal, 12: end, 3: step

array([ 2,  5,  8, 11])

In [ ]:
np.arange(2,6,5)

array([2])

In [ ]:
np.arange(3,10,3)

array([3, 6, 9])

##numpy.linspace

In [ ]:
import numpy as np
# Membuat urutan dari 0 hingga 1 dengan 5 elemen

urutan, jarak = np.linspace(0, 1, 5, retstep=True)
print("Urutan:", urutan)
print("Jarak antara elemen:", jarak)

Urutan: [0.   0.25 0.5  0.75 1.  ]
Jarak antara elemen: 0.25

In [ ]:
#Membuat urutan bilangan bulat dari 0 hingga 10 dengan 4 elemen dan tipe data integer
urutan = np.linspace(0, 10, 4, dtype=int)

print("Urutan:", urutan)

Urutan: [ 0  3  6 10]

In [ ]:
#Membuat urutan dengan num=5 tanpa menggunakan endpoint dan dengan menggunakan retstep
a = np.linspace(2.0, 3.0, num=5)
b = np.linspace(2.0, 3.0, num=5, endpoint=False)
c, step = np.linspace(2.0, 3.0, num=5, retstep=True)

# Menampilkan output
print("Urutan a (dengan endpoint):")
print(a)

print("\nUrutan b (tanpa endpoint):")
print(b)

print("\nUrutan c (dengan retstep):")
print(c)

print("\nJarak antara elemen dalam urutan c:")
print(step)

Urutan a (dengan endpoint):
[2.   2.25 2.5  2.75 3.  ]

Urutan b (tanpa endpoint):
[2.  2.2 2.4 2.6 2.8]

Urutan c (dengan retstep):
[2.   2.25 2.5  2.75 3.  ]

Jarak antara elemen dalam urutan c:
0.25

#PANDAS

In [ ]:
#P1
#Running pandas dan numpy
import pandas as pd
import numpy as np


#Menampilkan array 1-dimensi
ds = pd.Series([2, 4, 6, 8, 10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
#P2
data = pd.Series(['a','b','c'])
np1 = np.array(['x','y','z'])
data_np = pd.Series(np1)

print(data)
print(data_np)

#Mengatur indeks pada numpy array data-np di atas
data_np = pd.Series(np1, index=[2,3,4])
print(data_np)

0    a
1    b
2    c
dtype: object
0    x
1    y
2    z
dtype: object
2    x
3    y
4    z
dtype: object

In [ ]:
#P3 contoh operasi
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
dsa = ds1 + ds2  #operasi jumlah
dsb = ds1 - ds2
dsc = ds1 * ds2
dsd = ds1 / ds2
print(dsa)
print(dsb)
print(dsc)
print(dsd)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [ ]:
#P4 konver pandas module Series ke python list
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series dan type")
print(ds)
print(type(ds))

print("Konver Pandas Series ke Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series dan type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Konver Pandas Series ke Python list
[2, 4, 6, 8, 10]
<class 'list'>

In [ ]:
#P5 convert a NumPy array to a Pandas series
import numpy as np
import pandas as pd
np_array = np.array([0, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)

new_np = pd.Series(np_array)
print("konversi Pandas series:")
print(new_np)

NumPy array:
[ 0 20 30 40 50]
konversi Pandas series:
0     0
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
#P6
import pandas as pd
import numpy as np

#generate angka random
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))

print(num_series)
#print(num_state)

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/main/penjualan.csv')
df

      nama  jan  feb  mar  apr
0     Andi  100  135   85   75
1     Budi  200  240  185  160
2  Chandra  300  315  285  190
3     Dudi  250  270  230  200
4      Eko  150  195  110  100
5    Fahri   95  130   75   45
6     Gina  125  175  110   70
7   Herman  130  155  100   85
8   Indara  320  374  300  270
9     Joni  200  220  175  155

In [ ]:
df.head(3)

      nama  jan  feb  mar  apr
0     Andi  100  135   85   75
1     Budi  200  240  185  160
2  Chandra  300  315  285  190

In [ ]:
df.describe()

             jan         feb         mar         apr
count   10.00000   10.000000   10.000000   10.000000
mean   187.00000  220.900000  165.500000  135.000000
std     81.14459   80.161573   83.081285   71.608504
min     95.00000  130.000000   75.000000   45.000000
25%    126.25000  160.000000  102.500000   77.500000
50%    175.00000  207.500000  142.500000  127.500000
75%    237.50000  262.500000  218.750000  182.500000
max    320.00000  374.000000  300.000000  270.000000

##Load Data

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Alam-A99/DATAAKSI/main/dataset_fiskal_97_hipoFull.csv')
df

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
0,Kota Banda Aceh,2014,77.91,49.42,26.00,96.98,47.59,83.94,72.02,153.66,...,175.78,253.43,286.18,100.88,133.54,5.31,9.79,0.47,65.31,2.82
1,Kota Banda Aceh,2015,54.88,37.29,35.35,112.77,59.88,74.74,52.84,119.84,...,98.47,285.13,133.72,268.34,254.48,10.50,6.19,0.46,64.99,7.33
2,Kota Banda Aceh,2016,78.91,27.08,39.83,107.56,52.78,96.58,97.41,179.24,...,264.70,212.19,192.71,64.94,59.59,9.57,3.68,0.44,71.00,4.82
3,Kota Banda Aceh,2017,72.77,26.01,46.46,109.93,80.91,63.84,73.98,150.55,...,219.24,288.64,277.40,272.15,267.70,7.77,9.79,0.46,83.49,7.27
4,Kota Banda Aceh,2018,93.06,82.81,31.70,127.89,60.87,77.19,80.88,148.09,...,259.48,87.86,51.55,132.27,178.19,17.43,5.50,0.36,73.57,5.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,Kota Sorong,2020,116.28,67.28,73.72,156.21,142.40,94.42,141.83,174.79,...,146.82,114.70,132.38,143.36,54.51,13.70,9.22,0.39,78.66,3.45
1063,Kota Sorong,2021,138.49,113.67,57.69,173.31,83.56,99.41,91.17,248.49,...,214.92,129.11,160.15,145.88,189.26,7.77,3.27,0.31,80.79,4.39
1064,Kota Sorong,2022,105.81,108.63,41.69,232.20,125.93,92.21,130.82,274.78,...,160.51,71.74,264.24,259.16,246.84,11.44,9.03,0.33,66.97,2.12
1065,Kota Sorong,2023,80.40,49.05,63.66,137.98,94.78,101.75,126.07,265.28,...,212.06,125.80,221.05,212.70,185.33,16.30,9.80,0.46,84.08,6.63
1066,Kota Sorong,2024,94.64,79.05,72.16,206.04,111.61,138.26,169.47,181.43,...,65.36,291.64,270.61,203.54,130.97,16.54,8.06,0.49,83.27,3.03

In [ ]:
df.info('kota')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067 entries, 0 to 1066
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Kota                    1067 non-null   object
 1   Tahun                   1067 non-null   int64
 2   DBH_PAJAK               1067 non-null   float64
 3   DBH_SDA                 1067 non-null   float64
 4   DBH_Lainnya             1067 non-null   float64
 5   DAU_Grant               1067 non-null   float64
 6   DAU_Earmark             1067 non-null   float64
 7   DAK_Fisik               1067 non-null   float64
 8   DAK_Nonfisik            1067 non-null   float64
 9   PAD                     1067 non-null   float64
 10  ICT                     1067 non-null   float64
 11  bm_pendidikan           1067 non-null   float64
 12  bm_kesehatan            1067 non-null   float64
 13  bm_perumahan            1067 non-null   float64
 14  bm_lingkungan           1067 non-null   float64
 15  bm_ekonomi              1067 non-null   float64
 16  bm_infrastruktur        1067 non-null   float64
 17  bm_pariwisata           1067 non-null   float64
 18  bm_perlindungan_sosial  1067 non-null   float64
 19  KEMISKINAN              1067 non-null   float64
 20  PENGANGGURAN            1067 non-null   float64
 21  KETIMPANGAN             1067 non-null   float64
 22  IPM                     1067 non-null   float64
 23  PE                      1067 non-null   float64
dtypes: float64(22), int64(1), object(1)
memory usage: 200.2+ KB

In [ ]:
df.describe()

,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,ICT,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
count,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,...,1067.000000,1067.00000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,2019.000000,107.905464,71.138960,53.830628,178.029850,107.452034,107.783393,106.766401,215.204077,81.898013,...,172.587882,173.69358,174.611565,172.471546,171.014255,12.538519,6.466692,0.398641,72.378847,4.958547
std,3.163761,57.856235,42.449883,28.680751,87.999498,54.994876,56.152152,56.852234,110.345873,11.873095,...,71.441473,72.10115,72.044194,71.984621,71.837922,4.258490,2.033596,0.057334,7.211382,1.668266
min,2014.000000,11.550000,5.940000,6.190000,22.330000,12.260000,12.710000,13.420000,24.060000,60.630000,...,50.010000,50.06000,50.980000,50.060000,50.060000,5.000000,3.000000,0.300000,60.010000,2.000000
25%,2016.000000,69.770000,42.840000,34.390000,118.675000,69.420000,68.740000,65.130000,138.570000,71.000000,...,109.455000,111.02500,111.405000,110.245000,108.400000,9.055000,4.750000,0.350000,66.075000,3.590000
50%,2019.000000,96.720000,61.830000,47.760000,163.550000,98.520000,99.410000,95.910000,198.420000,82.030000,...,171.960000,170.87000,174.580000,170.560000,168.840000,12.470000,6.390000,0.400000,72.420000,4.960000
75%,2022.000000,137.460000,90.070000,68.720000,223.535000,137.480000,134.720000,135.945000,273.040000,92.340000,...,232.870000,237.29000,235.460000,236.230000,231.505000,16.140000,8.235000,0.450000,78.765000,6.345000
max,2024.000000,365.020000,278.510000,166.720000,582.960000,303.090000,353.440000,381.840000,686.780000,100.000000,...,299.890000,299.70000,299.870000,299.800000,299.360000,19.990000,10.000000,0.500000,84.950000,7.990000

In [ ]:
df.tail(4)

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
1063,Kota Sorong,2021,138.49,113.67,57.69,173.31,83.56,99.41,91.17,248.49,...,214.92,129.11,160.15,145.88,189.26,7.77,3.27,0.31,80.79,4.39
1064,Kota Sorong,2022,105.81,108.63,41.69,232.20,125.93,92.21,130.82,274.78,...,160.51,71.74,264.24,259.16,246.84,11.44,9.03,0.33,66.97,2.12
1065,Kota Sorong,2023,80.40,49.05,63.66,137.98,94.78,101.75,126.07,265.28,...,212.06,125.80,221.05,212.70,185.33,16.30,9.80,0.46,84.08,6.63
1066,Kota Sorong,2024,94.64,79.05,72.16,206.04,111.61,138.26,169.47,181.43,...,65.36,291.64,270.61,203.54,130.97,16.54,8.06,0.49,83.27,3.03

In [ ]:
df.head(3)

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
0,Kota Banda Aceh,2014,77.91,49.42,26.00,96.98,47.59,83.94,72.02,153.66,...,175.78,253.43,286.18,100.88,133.54,5.31,9.79,0.47,65.31,2.82
1,Kota Banda Aceh,2015,54.88,37.29,35.35,112.77,59.88,74.74,52.84,119.84,...,98.47,285.13,133.72,268.34,254.48,10.50,6.19,0.46,64.99,7.33
2,Kota Banda Aceh,2016,78.91,27.08,39.83,107.56,52.78,96.58,97.41,179.24,...,264.70,212.19,192.71,64.94,59.59,9.57,3.68,0.44,71.00,4.82

## Ekstrak dan manipulasi data frame

In [ ]:
#P8 menampilkan tabel penjulan februari Jalankan perintah P8 jika file ada di drive local

import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/main/penjualan.csv')

feb = df["feb"]
feb.head()

0    135
1    240
2    315
3    270
4    195
Name: feb, dtype: int64

In [ ]:
#P9 Jika akan menampilkan lebih dari satu kolom (Series), gukanan double bracket [[]]

df= pd.read_csv('https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/main/penjualan.csv')
df[['feb','mar']].head(3)

   feb  mar
0  135   85
1  240  185
2  315  285

In [ ]:
#P10.1

penjual = ['penjual no ' + str(i) for i in range(1, 11)]
penjual

['penjual no 1',
 'penjual no 2',
 'penjual no 3',
 'penjual no 4',
 'penjual no 5',
 'penjual no 6',
 'penjual no 7',
 'penjual no 8',
 'penjual no 9',
 'penjual no 10']

In [ ]:
#P10.2

df['urutan'] = penjual
df

      nama  jan  feb  mar  apr         urutan
0     Andi  100  135   85   75   penjual no 1
1     Budi  200  240  185  160   penjual no 2
2  Chandra  300  315  285  190   penjual no 3
3     Dudi  250  270  230  200   penjual no 4
4      Eko  150  195  110  100   penjual no 5
5    Fahri   95  130   75   45   penjual no 6
6     Gina  125  175  110   70   penjual no 7
7   Herman  130  155  100   85   penjual no 8
8   Indara  320  374  300  270   penjual no 9
9     Joni  200  220  175  155  penjual no 10

In [ ]:
#P11 Ekstraksi Angka dari Teks

df['no'] = df['urutan'].str.extract('(\d+)').astype('int64')
df

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_1175/855670444.py:3: SyntaxWarning: invalid escape sequence '\d'
  df['no'] = df['urutan'].str.extract('(\d+)').astype('int64')

      nama  jan  feb  mar  apr         urutan  no
0     Andi  100  135   85   75   penjual no 1   1
1     Budi  200  240  185  160   penjual no 2   2
2  Chandra  300  315  285  190   penjual no 3   3
3     Dudi  250  270  230  200   penjual no 4   4
4      Eko  150  195  110  100   penjual no 5   5
5    Fahri   95  130   75   45   penjual no 6   6
6     Gina  125  175  110   70   penjual no 7   7
7   Herman  130  155  100   85   penjual no 8   8
8   Indara  320  374  300  270   penjual no 9   9
9     Joni  200  220  175  155  penjual no 10  10